# Generated by Django 4.2.15 on 2024-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecharacter',
            name='character',
        ),
        migrations.AddField(
            model_name='favoritecharacter',
            name='character_id',
            field=models.IntegerField(null=True),
        ),
    ]
