# Generated by Django 4.2.15 on 2024-08-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlist_delete_moviewatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='video',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='video_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
